In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('/content/zonal_stats.xlsx')
df.head()

,Unnamed: 0,District,Mandal,Area(ha)_Category_0,Area(ha)_Category_1,Area(ha)_Category_2,Area(ha)_Category_3,Area(ha)_Category_4,Area(ha)_Category_5,Area(ha)_Category_6
0,0,Rangareddy,Abdullapurmet,24024.57,1080.78,0.00,0.00,127.82,63.37,10.72
1,1,Nagarkurnool,Achampet,43559.48,344.80,664.21,620.75,18.65,145.31,4998.99
2,2,Nalgonda,Adavidevulapally,9753.53,1575.49,0.00,0.00,0.00,803.41,430.16
3,3,Yadadri Bhuvanagiri,Addagudur,10304.10,3800.48,0.04,0.00,75.16,0.49,0.56
4,4,Mahabubnagar,Addakal,10772.45,2314.66,27.52,3.76,17.44,0.00,329.35

In [5]:
# Define your target columns
targets = ['Area(ha)_Category_1',
       'Area(ha)_Category_2', 'Area(ha)_Category_3', 'Area(ha)_Category_4',
       'Area(ha)_Category_5', 'Area(ha)_Category_6']  # Add more columns if needed

In [6]:
# Group by 'district' and calculate sum for each target column
sum_df = df.groupby('District')[targets].sum().reset_index()

In [7]:
# Rename columns with prefix 'sum_'
sum_df.columns = ['District'] + ['sum_' + col for col in targets]

In [8]:
sum_df.to_excel('sum_for_districts.xlsx')
sum_df

,District,sum_Area(ha)_Category_1,sum_Area(ha)_Category_2,sum_Area(ha)_Category_3,sum_Area(ha)_Category_4,sum_Area(ha)_Category_5,sum_Area(ha)_Category_6
0,Adilabad,258.03,4883.57,27428.83,12372.00,0.17,0.00
1,Bhadradri Kothagudem,28118.61,6135.95,328.17,2611.56,11673.83,1748.46
2,Hanumakonda,51201.11,13508.25,0.00,1319.65,3690.20,0.00
3,Hyderabad,5.67,0.00,0.00,5.18,11.04,0.40
4,Jagtial,93502.56,6554.52,0.11,4772.22,0.00,0.00
5,Jangoan,65975.16,5039.04,0.00,1259.89,3857.10,0.00
6,Jayashankar Bhupalpally,30170.18,3963.65,8.78,8.12,15237.78,0.00
7,Jogulamba Gadwal,17101.28,18770.42,7383.82,18943.77,7673.84,0.01
8,Kamareddy,97688.64,4983.52,22303.72,6022.07,0.00,0.00
9,Karimnagar,109741.62,6976.97,0.00,1098.73,2.73,0.00
10,Khammam,38102.36,28351.01,5024.66,2231.32,25190.48,1.03
11,Kumurambheem Asifabad,7730.06,1866.30,1619.40,2510.58,0.00,0.00
12,Mahabubabad,60590.86,16525.03,5.73,1642.62,16690.11,0.00
13,Mahabubnagar,35782.78,1550.32,35.28,963.99,4.04,12368.53
14,Mancherial,39144.84,1.77,1.87,2755.19,0.02,0.00
15,Medak,79524.34,850.31,1000.73,2181.71,0.00,0.00
16,Medchal_Malkajgiri,7157.13,1.05,2.56,1034.82,0.44,0.01
17,Mulugu,24158.76,1877.57,2329.96,0.22,12710.28,0.00
18,Nagarkurnool,34512.61,6729.74,5847.00,1724.61,4376.70,52761.22
19,Nalgonda,172299.53,2.79,3.73,12.94,11244.10,8905.40
20,Narayanpet,34231.60,1.87,1636.56,963.56,0.00,9548.94
21,Nirmal,46742.94,32073.34,17151.67,3.84,7528.89,0.00
22,Nizamabad,161057.23,17615.03,9140.69,10588.69,0.13,0.00
23,Peddapalli,80297.18,4656.65,0.00,0.34,0.02,0.00
24,Rajanna Sircilla,65523.06,703.92,2.25,1419.97,0.00,0.00
25,Rangareddy,38078.97,16.28,20.87,2811.21,4404.99,3271.17
26,Sangareddy,39110.41,2651.47,7859.40,9384.23,0.20,1.07
27,Siddipet,76211.50,10187.13,430.19,4761.52,5.57,0.00
28,Suryapet,155321.39,11.85,0.00,3.70,12275.90,0.16
29,Vikarabad,31187.44,1956.18,3157.86,3489.03,5.51,9836.13
30,Wanaparthy,35907.02,24.87,5258.48,2704.07,12.15,11770.68
31,Warangal,40450.28,30804.13,3.75,152.80,6811.33,0.00
32,Yadadri Bhuvanagiri,96155.27,729.32,0.00,2430.28,236.39,0.83